steps:
- name: 'gcr.io/cloud-builders/docker'
  agrs: ['build', '-t', 'gcr.io/$PROJECT_ID/winequalityclassifier-webapp:v1', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  agrs: ['push', 'gcr.io/$PROJECT_ID/winequalityclassifier-webapp:v1']
- name: 'gcr.io/cloud-builders/gke-deploy'
  agrs:
  - run
  - --filename=k8s/
  - --location=us-west1-b
  - --cluster=project-kube